home_index:
    path: /
    controller: App\Controller\HomeController::index

calendar_index:
    path: /calendrier
    controller: App\Controller\CalendarController::index


registration_register:
    path: registration/
    controller: App\Controller\RegistrationController::register

security_login:
    path: security/
    controller: App\Controller\SecurityController::login

security_logout:
    path: security/deconnexion
    controller: App\Controller\SecurityController::logout

api_event_edit:
    methods: GET|POST
    path: /api/{id}/edit
    controller: App\Controller\SecurityController::majEvent

#
## Contact
#

contact_index:
    path: /contact/
    controller: App\Controller\ContactController::index

contact_create:
    path: /contact/new
    controller: App\Controller\ContactController::form

contact_edit:
    path: /contact/{id}/edit
    controller: App\Controller\ContactController::form

contact_show:
    methods: GET
    path: /contact/show/{id}
    controller: App\Controller\ContactController::show

contact_delete:
    path: /contact/delete/{id}
    controller: App\Controller\ContactController::delete

#
## profil
#

profil_index:
    path: /profil/
    controller: App\Controller\ProfilController::index

#
## dashboard
#

dashboard_index:
    path: /dashboard/
    controller: App\Controller\DashboardController::index
