#
## home
#

home_index:
    path: /
    controller: App\Controller\HomeController::index

#
## calendar
#

calendar_index:
    path: /calendrier
    controller: App\Controller\CalendarController::index

#
## registration
#

registration_register:
    path: /registration/
    controller: App\Controller\RegistrationController::register

registration_activation:
    path: /registration/activation/{token}
    controller: App\Controller\RegistrationController::activation

#
## security
#

security_login:
    path: /security/
    controller: App\Controller\SecurityController::login

security_logout:
    path: /security/deconnexion
    controller: App\Controller\SecurityController::logout

security_forgottenpass:
    path: /security/forgottenpass
    controller: App\Controller\SecurityController::forgottenPass

security_resetpass:
    path: /security/resetpass/{token}
    controller: App\Controller\SecurityController::resetPass

security_legalnotices:
    path: /legalnotices/
    controller: App\Controller\SecurityController::legalnotices

security_privacypolicy:
    path: /privacypolicy/
    controller: App\Controller\SecurityController::privacypolicy




#
## Contact
#

contact_index:
    path: /contact/
    controller: App\Controller\ContactController::index

contact_create:
    path: /contact/new
    controller: App\Controller\ContactController::form

contact_edit:
    path: /contact/{id}/edit
    controller: App\Controller\ContactController::form

contact_show:
    methods: GET
    path: /contact/show/{id}
    controller: App\Controller\ContactController::show

contact_delete:
    path: /contact/delete/{id}
    controller: App\Controller\ContactController::delete

#
## profil
#

profil_index:
    path: /profil/
    controller: App\Controller\ProfilController::index

profil_events_new:
    path: /profil/evenements/ajout
    controller: App\Controller\ProfilController::newEvent

profil_edit:
    path: /profil/edit
    controller: App\Controller\ProfilController::editProfil

profil_editpass:
    path: /profil/editpassword
    controller: App\Controller\ProfilController::editPassword

#
## dashboard
#

dashboard_index:
    path: /dashboard/
    controller: App\Controller\DashboardController::index

#
## admin
#

admin_index:
    path: /admin/
    controller: App\Controller\AdminController::index

admin_users:
    path: /admin/utilisateurs
    controller: App\Controller\AdminController::userList

admin_modifier:
    methods: GET|POST
    path: /admin/utilisateur/modifier/{id}
    controller: App\Controller\AdminController::editUser